// src/flightData.js

const flightData = [
    {
        airlineName: "Airline A",
        airlineLogo: "https://example.com/logo-a.png",
        fromLocation: "Los Angeles International Airport",
        toLocation: "John F. Kennedy International Airport",
        price: "$500",
        duration: "5h 30m",
        departureTime: "2025-10-10T08:00:00",
        arrivalTime: "2025-10-10T14:30:00",
    },
    {
        airlineName: "Airline B",
        airlineLogo: "https://example.com/logo-b.png",
        fromLocation: "San Francisco International Airport",
        toLocation: "O'Hare International Airport",
        price: "$450",
        duration: "4h 45m",
        departureTime: "2025-10-12T09:15:00",
        arrivalTime: "2025-10-12T15:00:00",
    },
    {
        airlineName: "Airline C",
        airlineLogo: "https://example.com/logo-c.png",
        fromLocation: "Miami International Airport",
        toLocation: "Dallas/Fort Worth International Airport",
        price: "$320",
        duration: "3h 20m",
        departureTime: "2025-10-15T11:00:00",
        arrivalTime: "2025-10-15T14:20:00",
    },
    {
        airlineName: "Airline D",
        airlineLogo: "https://example.com/logo-d.png",
        fromLocation: "Seattle-Tacoma International Airport",
        toLocation: "Denver International Airport",
        price: "$370",
        duration: "2h 50m",
        departureTime: "2025-10-17T10:30:00",
        arrivalTime: "2025-10-17T13:20:00",
    },
    {
        airlineName: "Airline E",
        airlineLogo: "https://example.com/logo-e.png",
        fromLocation: "Boston Logan International Airport",
        toLocation: "San Diego International Airport",
        price: "$550",
        duration: "6h 10m",
        departureTime: "2025-10-18T14:00:00",
        arrivalTime: "2025-10-18T20:10:00",
    },
    {
        airlineName: "Airline F",
        airlineLogo: "https://example.com/logo-f.png",
        fromLocation: "Chicago O'Hare International Airport",
        toLocation: "Miami International Airport",
        price: "$480",
        duration: "3h 45m",
        departureTime: "2025-10-20T12:00:00",
        arrivalTime: "2025-10-20T15:45:00",
    },
    {
        airlineName: "Airline G",
        airlineLogo: "https://example.com/logo-g.png",
        fromLocation: "Phoenix Sky Harbor International Airport",
        toLocation: "Newark Liberty International Airport",
        price: "$410",
        duration: "4h 10m",
        departureTime: "2025-10-22T13:30:00",
        arrivalTime: "2025-10-22T17:40:00",
    },
    {
        airlineName: "Airline H",
        airlineLogo: "https://example.com/logo-h.png",
        fromLocation: "Atlanta Hartsfield-Jackson International Airport",
        toLocation: "Salt Lake City International Airport",
        price: "$360",
        duration: "3h 5m",
        departureTime: "2025-10-24T07:00:00",
        arrivalTime: "2025-10-24T10:05:00",
    },
    {
        airlineName: "Airline I",
        airlineLogo: "https://example.com/logo-i.png",
        fromLocation: "Minneapolis-Saint Paul International Airport",
        toLocation: "Detroit Metropolitan Airport",
        price: "$390",
        duration: "2h 55m",
        departureTime: "2025-10-26T16:30:00",
        arrivalTime: "2025-10-26T19:25:00",
    },
    {
        airlineName: "Airline J",
        airlineLogo: "https://example.com/logo-j.png",
        fromLocation: "Charlotte Douglas International Airport",
        toLocation: "Philadelphia International Airport",
        price: "$430",
        duration: "1h 55m",
        departureTime: "2025-10-28T17:45:00",
        arrivalTime: "2025-10-28T19:40:00",
    },
];

export default flightData;
